# Generated by Django 3.2.7 on 2021-09-13 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_commenet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenet',
            name='time',
            field=models.TimeField(),
        ),
    ]
