# Generated by Django 3.2.6 on 2021-08-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='categorya',
            field=models.CharField(choices=[('SP', 'спорт'), ('PO', 'политика'), ('SH', 'образование'), ('OT', 'другое')], default='SH', max_length=32, unique=True),
        ),
    ]
